import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import TopBar from "@/components/TopBar";
import Footer from "@/components/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const satoshi = localFont({
  src: "./fonts/Satoshi-Regular.otf",
  variable: "--satoshi",
  weight: "100 900",
});
const satoshimed = localFont({
  src: "./fonts/Satoshi-Medium.otf",
  variable: "--satoshi-med",
  weight: "100 900",
});
const satoshiBold = localFont({
  src: "./fonts/Satoshi-Bold.otf",
  variable: "--satoshi-bold",
  weight: "100 900",
});
const integ = localFont({
  src: "./fonts/Fontspring-DEMO-integralcf-regular.otf",
  variable: "--integ",
  weight: "100 900",
});
const integmed = localFont({
  src: "./fonts/Fontspring-DEMO-integralcf-medium.otf",
  variable: "--integ-med",
  weight: "100 900",
});
const integBold = localFont({
  src: "./fonts/Fontspring-DEMO-integralcf-bold.otf",
  variable: "--integ-bold",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Fontspring-DEMO-integralcf-regular.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${integBold.variable} ${satoshiBold.variable} ${geistMono.variable} ${integ.variable} ${satoshi.variable}
        ${satoshimed.variable} ${integmed.variable}  antialiased bg-[#9A9A9A]`}
      >
        <div className="max-w-screen-large mx-auto bg-white">
          <TopBar />
          <Header />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
